# Generated by Django 4.2.2 on 2023-07-17 14:46

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_name', models.CharField(max_length=30, verbose_name='Marca')),
            ],
        ),
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color_name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transmission', models.CharField(choices=[('A', 'Automático'), ('M', 'Manual')], max_length=1, verbose_name='transmission')),
                ('fuel_type', models.CharField(choices=[('GAS', 'Gasolina'), ('ETH', 'Etanol'), ('FLE', 'Flex'), ('DIE', 'Diesel'), ('ELE', 'Elétrico')], max_length=3, verbose_name='fuel type')),
                ('purchase_price', models.FloatField(default=0, verbose_name='Preço de compra')),
                ('sale_value', models.FloatField(blank=True, default=0, null=True, verbose_name='Preço de venda')),
                ('mileage', models.IntegerField(default=0, verbose_name='Quilometragem')),
                ('number_of_doors', models.IntegerField(default=2, null=True, verbose_name='Número de portas')),
                ('license_plate', models.CharField(max_length=7, null=True, verbose_name='Placa')),
                ('model_year', models.IntegerField(default=2023, validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(9999)], verbose_name='Ano modelo')),
                ('manufacture_year', models.IntegerField(default=2023, validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(9999)], verbose_name='Ano fabricação')),
                ('salesman_observation', models.TextField(default='')),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.color', verbose_name='Cor')),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle_cost_type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost_name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(max_length=30, verbose_name='Modelo')),
                ('model_type', models.CharField(choices=[('M', 'Moto'), ('C', 'Carro'), ('T', 'Caminhão')], max_length=1, verbose_name='Tipo')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='brand', to='erp.brand', verbose_name='Marca')),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle_model_variant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('variant_name', models.CharField(max_length=30)),
                ('vehicle_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='erp.vehicle_model')),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle_image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.ImageField(upload_to='images/')),
                ('index', models.IntegerField(null=True)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicle', to='erp.vehicle')),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle_cost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost_name', models.CharField(max_length=30)),
                ('expense_date', models.DateField()),
                ('value', models.FloatField(blank=True, null=True)),
                ('cost_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.vehicle_cost_type')),
            ],
        ),
        migrations.AddField(
            model_name='vehicle',
            name='vehicle_variant',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='variant', to='erp.vehicle_model_variant'),
        ),
    ]
