# Generated by Django 4.1 on 2023-04-10 18:02

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle_cost_type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost_name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(max_length=30)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='models', to='erp.brand')),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle_model_variant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('variant_name', models.CharField(max_length=30)),
                ('vehicle_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='models', to='erp.vehicle_model')),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle_cost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost_name', models.CharField(max_length=30)),
                ('expense_date', models.DateField()),
                ('value', models.FloatField(blank=True, null=True)),
                ('cost_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.vehicle_cost_type')),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transmission', models.CharField(choices=[('A', 'Automatic'), ('M', 'Manual')], max_length=1)),
                ('fuel_type', models.CharField(choices=[('G', 'Gasoline'), ('E', 'Ethanol'), ('F', 'Flex'), ('D', 'Diesel')], max_length=1)),
                ('purchase_price', models.FloatField(default=0)),
                ('sale_value', models.FloatField(blank=True, null=True)),
                ('mileage', models.IntegerField(default=0)),
                ('number_of_doors', models.IntegerField(default=2, null=True)),
                ('license_plate', models.CharField(max_length=7, null=True)),
                ('year', models.IntegerField(default=2023, validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(9999)])),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.color')),
                ('vehicle_variant', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vehicles', to='erp.vehicle_model_variant')),
            ],
        ),
    ]
