# Generated by Django 4.1 on 2023-04-10 18:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='vehicle_variant',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='variant', to='erp.vehicle_model_variant'),
        ),
        migrations.AlterField(
            model_name='vehicle_model',
            name='brand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='brand', to='erp.brand'),
        ),
        migrations.AlterField(
            model_name='vehicle_model_variant',
            name='vehicle_model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='model', to='erp.vehicle_model'),
        ),
        migrations.CreateModel(
            name='Vehicle_image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.ImageField(upload_to='images/')),
                ('index', models.IntegerField(null=True)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicle', to='erp.vehicle')),
            ],
        ),
    ]
