# Generated by Django 4.1 on 2023-05-09 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0004_rename_year_vehicle_manufacture_year_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='salesman_observation',
            field=models.TextField(default=''),
        ),
    ]
