# Generated by Django 4.1.6 on 2023-05-10 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0005_vehicle_salesman_observation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='fuel_type',
            field=models.CharField(choices=[('GAS', 'Gasoline'), ('ETH', 'Ethanol'), ('FLE', 'Flex'), ('DIE', 'Diesel'), ('ELE', 'Eletric')], max_length=3),
        ),
    ]
