# Generated by Django 4.2.2 on 2023-06-24 14:12

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0006_alter_vehicle_fuel_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='color',
            old_name='name',
            new_name='color_name',
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='color',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.color', verbose_name='Cor'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='fuel_type',
            field=models.CharField(choices=[('GAS', 'Gasolina'), ('ETH', 'Etanol'), ('FLE', 'Flex'), ('DIE', 'Diesel'), ('ELE', 'Elétrico')], max_length=3, verbose_name='fuel type'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='license_plate',
            field=models.CharField(max_length=7, null=True, verbose_name='Placa'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='manufacture_year',
            field=models.IntegerField(default=2023, validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(9999)], verbose_name='Ano fabricação'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='mileage',
            field=models.IntegerField(default=0, verbose_name='Quilometragem'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='model_year',
            field=models.IntegerField(default=2023, validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(9999)], verbose_name='Ano modelo'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='number_of_doors',
            field=models.IntegerField(default=2, null=True, verbose_name='Número de portas'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='purchase_price',
            field=models.FloatField(default=0, verbose_name='Preço de compra'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='sale_value',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Preço de venda'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='transmission',
            field=models.CharField(choices=[('A', 'Automático'), ('M', 'Manual')], max_length=1, verbose_name='transmission'),
        ),
        migrations.AlterField(
            model_name='vehicle_model',
            name='model_type',
            field=models.CharField(choices=[('M', 'Moto'), ('C', 'Carro'), ('T', 'Caminhão')], max_length=1),
        ),
    ]
