# Generated by Django 4.2.2 on 2023-07-17 14:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=30, null=True)),
                ('document', models.CharField(blank=True, max_length=30, null=True)),
                ('instagram_link', models.URLField(blank=True, null=True)),
                ('facebook_link', models.URLField(blank=True, null=True)),
                ('whatsapp_number', models.CharField(blank=True, max_length=13, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=30)),
                ('address_street', models.CharField(blank=True, max_length=50, null=True)),
                ('address_zipcode', models.CharField(blank=True, max_length=8, null=True)),
                ('address_number', models.IntegerField(blank=True, null=True)),
                ('address_complement', models.CharField(blank=True, max_length=50, null=True)),
                ('address_neighborhood', models.CharField(blank=True, max_length=50, null=True)),
                ('address_city', models.CharField(blank=True, max_length=50, null=True)),
                ('address_state', models.CharField(blank=True, max_length=2, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shops', to='companies.company')),
            ],
        ),
    ]
