# Generated by Django 4.1 on 2023-05-14 19:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('document', models.CharField(max_length=30)),
                ('instagram_link', models.URLField()),
                ('facebook_link', models.URLField()),
                ('whatsapp_number', models.CharField(max_length=13)),
            ],
        ),
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address_street', models.CharField(max_length=50)),
                ('address_zipcode', models.CharField(max_length=8)),
                ('address_number', models.IntegerField()),
                ('address_complement', models.CharField(max_length=50)),
                ('address_city', models.CharField(max_length=50)),
                ('address_state', models.CharField(max_length=2)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shops', to='companies.company')),
            ],
        ),
    ]
