# Generated by Django 4.1 on 2023-05-14 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='name',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='company',
            name='document',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='facebook_link',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='instagram_link',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='name',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='whatsapp_number',
            field=models.CharField(max_length=13, null=True),
        ),
        migrations.AlterField(
            model_name='shop',
            name='address_city',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='shop',
            name='address_complement',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='shop',
            name='address_number',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='shop',
            name='address_state',
            field=models.CharField(max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='shop',
            name='address_street',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='shop',
            name='address_zipcode',
            field=models.CharField(max_length=8, null=True),
        ),
    ]
