# Generated by Django 4.1 on 2023-05-14 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0003_alter_company_document_alter_company_facebook_link_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='address_neighborhood',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
